name: Android Main CI
on: [push]
jobs:
  test_emulator:
    name: Test - ${{matrix.runs-on}}
    timeout-minutes: 30 # Emulator can get stuck
    runs-on: ${{matrix.runs-on}}
    strategy:
      fail-fast: true
      matrix:
        api-level: [ 16, 19, 28 ]
        runs-on: [buildjet-2vcpu-ubuntu-2004, macos-latest, buildjet-2vcpu-ubuntu-2204]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Java 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
            ~/.android/debug.keystore
          key: avd-${{ matrix.api-level }}
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          sdcard-path-or-size: 100M
          arch: x86
          ram-size: 2048M
          channel: canary
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          sdcard-path-or-size: 100M
          arch: x86
          ram-size: 2048M
          channel: canary
          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew :app:connectedCheck
